### ISSUE TITLE
Non-Cartesian MR reconstruction: would it be possible to code a new (spiral) trajectory to work with?

### ISSUE THREAD

**Issue by mscipio** [SyneRBI/SIRF#1054]
Hi everyone,

I have just started working on a project similar to [this SIRF contribution](https://github.com/SyneRBI/SIRF-Contribs/blob/130223d9bc11991eadcd11f9b715aea34c4842fd/src/Python/sirf/contrib/MCIR) involving MCIR based on a stack-of-spiral UTE sequence, for the MR part of the protocol, and I wanted to see if I could use SIRF functionalities for that. 

I saw that a recent merge introduced functionalities to deal with radial sequences (e.g. #1008 )

I was wondering how specific the code developed for the radial stack-of-stars is, and how hard it would be to develop a similar class to manage different (but also rather similar) types of encoding, like the one I am dealing with.

**ETA**:
I am aware that other packages that are able to perform NUFFT operations (_e.g. sigpy, gpunufft, torchkbnufft,.._) have a generic NUFFT class that accepts the trajectory as an input. I guess what I am wondering here is if it is possible with SIRF (or probably I should say with Gadgetron) to do the same, that is, passing a non-cartesian kspace, and the correct non-cartesian trajectory to a NUFFT operator, to perform the inversion.

---
On a related, but separate note, I successfully managed to run the example at [noncartesian_recon.py](https://github.com/SyneRBI/SIRF/blob/ac8a4f63e678978338b58a48b10809ffec137d12/examples/Python/MR/noncartesian_recon.py), but when I try to run the following one ([noncartesian_cg_sense.py](https://github.com/SyneRBI/SIRF/blob/ac8a4f63e678978338b58a48b10809ffec137d12/examples/Python/MR/noncartesian_cg_sense.py) at some point (and that point changes during multiple runs), my Gadgetron connection starts hanging and the execution stops.

Has anyone else experienced something like this and has a suggestion to share?
I could open a separate issue for the problem related to the example code if you prefer ...

Thanks a lot!

**Comment by johannesmayer** [comment]
I believe the radial 2D encoding with spirals could be implemented without large difficulties.
What one would need to implement is simply a computation of the trajectory for each acquisition.

The way SIRF does MR reconstruction is that you call a function on all the MR data that you have and it will compute that trajectory automatically (for example if you know your data are radially acquired then  you call `ret_radial2D_trajectory` after you loaded the data and from then on it will know what to do with them, no need to compute it yourself.)

For radial data, this is relatively straightforward,  so this is implemented at the C++ level, but I guess for spirals you will want to apply a correction because the actual trajectory played out in the scanner differs from the mathematically idealised version? 

So maybe it would make more sense to be able to pass the trajectory to SIRF directly instead of implementing these things in C++. I could expose a setter for the trajectory points and then the acquisition model should be able to handle it.

Are all the different slices in your stack encoded with identical spirals?

**Comment by mscipio** [comment]
Hi @johannesmayer,

yes, the sequence we are using is a multi-echo with spiral sampling in the x-y plane and cartesian sampling in the partition direction. Each spiral is sampled for all the partitions before moving to the next one, and the angles' sequence is based on golden angle.

So far we have not had success in computing the trajectory analytically - and it might be, as you suggested, that there are subtle differences between what's written down on paper and what actually happens in the scanner. So far we have been using (not with SIRF, yet) the trajectory as it is saved in log files during the acquisition itself. 

> it would make more sense to be able to pass the trajectory to SIRF directly instead of implementing these things in C++. I could expose a setter for the trajectory points and then the acquisition model should be able to handle it.

I believe that this would be a very good way to approach the solution, at least at this prototyping stage.

**Comment by KrisThielemans** [comment]
fixed by #1098
