### ISSUE TITLE
tests write GadgetronImagesVector::set_up_geom_info warnings

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#884]
Our tests write lots of these
https://travis-ci.com/github/SyneRBI/SIRF/jobs/491795031#L13658
```
GadgetronImagesVector::set_up_geom_info(): read_dir, phase_dir and slice_dir should all be unit vectors.
```
This is worrying, as well as causing log-size problems on Travis.

**Comment by KrisThielemans** [comment]
I'm not sure about that fix... Why does the warning trip? It shouldn't.

**Comment by evgueni-ovtchinnikov** [comment]
so far as I can see, the message "warns" that geometry set up failed, so it is essentially error message - apparently, Richard did not consider this kind of error fatal

**Comment by KrisThielemans** [comment]
@rijobro do you remember?

**Comment by rijobro** [comment]
I think we didn't consider it fatal as most users wouldn't care about converting `GadgetronImageData` to `RegImageData` or `STIRImageData`, so they wouldn't care that we didn't manage to calculate the geometry. 

Is this a warning that you weren't seeing previously and have started seeing recently? No idea why that would happen. 

I suppose you'll have to run the tests locally and print `read_dir`, `phase_dir` and `slice_dir` to see which ones aren't unit vectors and why. And on which datasets this happens.

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov could you check this?

I am very uncomfortable with having wrong information in classes. Certainly now that we've silenced any warnings.

**Comment by rijobro** [comment]
If I remember correctly, the image won't have wrong info. If it fails to calculate the geometrical information (it looks like here because it thinks the 3 directions aren't orthogonal to each other), then the geom info will be blank. See [here](https://github.com/SyneRBI/SIRF/blob/master/src/xGadgetron/cGadgetron/gadgetron_data_containers.cpp#L1662), where the object only gets created at the end of the method, once all other checks have passed.

**Comment by KrisThielemans** [comment]
ok. I see that `get_geom_info_sptr` throws if it isn't set-up.
https://github.com/SyneRBI/SIRF/blob/5f47af99304fad034637eb8accf57a1ce5df3991/src/common/include/sirf/common/ImageData.h#L118

So this seems safe, but nevertheless a puzzle. Why does it appear in our test data? Possibly something wrong with how it was generated. (@johannesmayer are you generating the test data now in #172 ?).

I'd feel more comfortable if we fix the test data and reinstate the warning, but I guess the urgency is off.

**Comment by rijobro** [comment]
It would be useful to print `read_dir`, `phase_dir` and `slice_dir` to see why it is that it's failing. Perhaps some are all zeros, or perhaps some are in the same direction. Do you know if this is a new issue?

**Comment by KrisThielemans** [comment]
I don't know if this is a new issue.

**Comment by evgueni-ovtchinnikov** [comment]
This is a very old issue, and it is actually an ISMRMRD one: their `generate_cartesian_shepp_logan` executable that we used to generate `simulated_MR_2D_cartesian.h5` and `simulated_MR_2D_cartesian_Grappa2.h5` generates them with zero `read_dir`, `phase_dir` and `slice_dir`.

Now that @DANAJK  apparently has his own Shepp-Logan generator that assigns proper non-zero values to `read_dir`, `phase_dir` and `slice_dir`, he could use it to update `simulated_MR_2D_cartesian.h5` and `simulated_MR_2D_cartesian_Grappa2.h5`, and `set_up_geom_info` would throw  instead of printing warnings.

**Comment by johannesmayer** [comment]
Would this contradict generating the test-data during build to be flexible w.r.t the ISMRMRD Header version?

**Comment by evgueni-ovtchinnikov** [comment]
@johannesmayer: if we go for test data generation during build, then ISMRMRD Shepp-Logan generator must be fixed first. Assigning proper values to `read_dir`, `phase_dir` and `slice_dir` (e.g. `1,0,0`, `0,1,0`, `0,0,1`) in `generate_cartesian_shepp_logan` should not take you long - can you create a PR at github.com/ismrmrd?

**Comment by johannesmayer** [comment]
If it is guaranteed that we can build against ISMRMRD/master then I would be happy to quickly write and submit this.

**Comment by KrisThielemans** [comment]
> If it is guaranteed that we can build against ISMRMRD/master

that might be a stretch. If they would be happy to create a release, then we could do this.

Stupid question (to which I should know the answer): why do we need `generate_cartesian_shepp_logan`. Can we do this ourselves?

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans: As you might have noticed, I started writing a corrected version of `generate_cartesian_shepp_logan` some time ago, but stopped because I felt terribly uneasy copying 99.9% of the ISMRMRD generator code into SIRF - to be thrown away once the ISMRMRD code is properly fixed.

**Comment by DANAJK** [comment]
1. The ISMRMRD  `read_dir`, `phase_dir` and `slice_dir` are not the best names and there has been some discussion about changing them. (They should really be something like `dim1_dir`, `dim2_dir`, `dim3_dir` with a separate field to denote the physical phase direction etc. ) . Changes are likely to be backwards compatible.
2. Should we use `NaN` to denote geometry properties that are not set, uncertain etc? This has a few advantages: a) any inadvertent use of the values propagates a `NaN` so it is obvious, b) someone concentrating on say, resampling, who knows their work should change the `offset`, but finds it hard to compute the correct value, could set `offset` to `NaN` and focus on their resampling without leaving dangerously wrong values in `offset`, c) it might simplify your tests.

**Comment by evgueni-ovtchinnikov** [comment]
I edited `simulated_MR_2D_cartesian.h5` and `simulated_MR_2D_cartesian_Grappa2.h5`, making `read_dir`, `phase_dir` and `slice_dir` unit vectors. Since `data` is a submodule of `SIRF`, what is the correct procedure for committing and pushing? (I ran into problems in the past with this submodule, ending up in some weird situations.) Do I first `cd data` and commit + push there and then go up and commit + push again?
