### ISSUE TITLE
MR Acquisition*.parameter_info() doc incomplete

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#947]
`AcquisitionData` doesn't give any clue what parameters I should pass
https://github.com/SyneRBI/SIRF/blob/a6573fc2b252e380ad00290dbd3b4d360940b343/src/xGadgetron/pGadgetron/Gadgetron.py#L923-L925
and `ImageData` talks about `Image` but that still doesn't tell me what to do
https://github.com/SyneRBI/SIRF/blob/a6573fc2b252e380ad00290dbd3b4d360940b343/src/xGadgetron/pGadgetron/Gadgetron.py#L307-L310

I only checked the Python doc.

**Comment by KrisThielemans** [comment]
The first should refer to `Acquisition`. Ideally include an example, and probably should recommend to do help(sirf.Gadgetron.Acquisition).

**Comment by KrisThielemans** [comment]
actually, all the PET `parameter_info()` functions return a string. This returns an array. I don't think it's a good idea to have 2 functions with the same name that do different things.

What about renaming this to `get_kspace_info()` or something like that? @ckolbPTB @johannesmayer what do you think? (It used to be called `get_info`)

**Comment by KrisThielemans** [comment]
Current `ImageData` doc:
https://github.com/SyneRBI/SIRF/blob/5d03c17d17972599357afe530a26fef2bffd5fc6/src/xGadgetron/pGadgetron/Gadgetron.py#L305-L320

@DANAJK @ckolbPTB @johannesmayer Does this make sense? (What does `slice` mean anyway?)

`AcquisitionData` doc:
https://github.com/SyneRBI/SIRF/blob/5d03c17d17972599357afe530a26fef2bffd5fc6/src/xGadgetron/pGadgetron/Gadgetron.py#L932-L943

What about calling this function `get_ISMRMRD_info`?

**Comment by ckolbPTB** [comment]
I think both `get_kspace_info()` and `get_ISMRMRD_info` would be fine. I guess the latter would provide the user already with the information that you can get ISMRMRD k-space parameters with this function. 

I would not use `slice` because it means multiple slices from a multi-slice 2D acquisition (which is not a 3D acquisition) and hence very confusing. Maybe use `average` or `acquisition_time_stamp`

For k-space, I would use `kspace_encode_step_1` which refers to phase encoding which every raw data should have.

**Comment by KrisThielemans** [comment]
ok. All implemented in https://github.com/SyneRBI/SIRF/pull/962. have a look there please.
